server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/ELBEQQAL94/eagle-microservices-config-repo
          searchPaths: licensingservice